services:
  - type: web
    name: ges-bank-api
    runtime: docker
    buildCommand: "./build.sh"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromService:
          type: pserv
          name: ges-bank-db
          property: host
      - key: DB_PORT
        fromService:
          type: pserv
          name: ges-bank-db
          property: port
      - key: DB_DATABASE
        fromService:
          type: pserv
          name: ges-bank-db
          property: database
      - key: DB_USERNAME
        fromService:
          type: pserv
          name: ges-bank-db
          property: user
      - key: DB_PASSWORD
        fromService:
          type: pserv
          name: ges-bank-db
          property: password
      - key: L5_SWAGGER_GENERATE_ALWAYS
        value: false

  - type: pserv
    name: ges-bank-db
    runtime: postgres
    plan: starter
