services:
  - type: web
    name: ges-bank-api
    runtime: docker
    buildCommand: "./build.sh"
    startCommand: "docker run -p 80:80 ges-bank"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d3v8l6ali9vc73ckvc00-a.oregon-postgres.render.com
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: bank_laravel_api
      - key: DB_USERNAME
        value: bank_laravel_api_user
      - key: DB_PASSWORD
        value: zNk24j1UwvkG8eM9P4EyUJ8lBj2vzczX
      - key: L5_SWAGGER_GENERATE_ALWAYS
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: ges-bank-api
          property: host

